I wanted a bare-bones program for SDL2 + OpenGL 2D rendering that also compiled to JS+WebGL with Emscripten. There are some SDL2 + OpenGL tutorials out there but most of them don't target the WebGL subset of OpenGL. I can't use the fixed function pipeline, so older OpenGL code won't work, and I can't use newer things like vertex array objects, instancing, or geometry shaders, so newer OpenGL code often won't work.

* Structure

My rough plan:

Each rendering layer will have one shader program, one set of vertex buffer objects, and one set of sprites drawn in a single draw call. The images for the sprites must be stored in a single texture atlas.

* Installation

On the Mac I installed these libraries for compilation:

#+begin_src sh
brew install SDL2 SDL2_image emscripten
git submodule init
git submodule update
#+end_src

To run the native code:

#+begin_src sh
make && bin/main
#+end_src

To run the emscripten code:

#+begin_src sh
make emscripten
#+end_src

and then tell the webserver to serve the files from =bin/=.

The Emscripten-ed output is [[http://www.redblobgames.com/x/1535-opengl-emscripten/html/][here]].

The font included in this project is [[https://www.google.com/fonts/specimen/Share+Tech+Mono][Share Tech Mono]], under the SIL Open Font License 1.1.
