[[http://unmaintained.tech/][http://unmaintained.tech/badge.svg]]

I wanted a bare-bones program for SDL2 + OpenGL 2D rendering that also compiled to JS+WebGL with Emscripten+Wasm. There are some SDL2 + OpenGL tutorials out there but most of them don't target the WebGL subset of OpenGL. I can't use the fixed function pipeline, so older OpenGL code won't work, and I can't use newer things like vertex array objects, instancing, or geometry shaders, so newer OpenGL code often won't work.

* Installation

Simplest is usually using [Docker](https://www.docker.com/), once install run:

#+begin_src sh
docker build -t builder .
docker run --rm -it -v $PWD:/code -v emcache:/root/.emscripten_cache -p 8080:8080 builder
#+end_src

Once done this would generate =bin/main=, a native Linux binary (needing SDL2 and SDL2 Image libraries), and run a server serving the WebAssembly page your can see by going to http://localhost:8080 from your machine.

Another option is using the Makefile which works on Mac OS X and Linux and possibly Windows and other SDL+OpenGL platforms (I haven't tried though). On Mac I installed these libraries for compilation:

#+begin_src sh
brew install SDL2 SDL2_image emscripten
git submodule init
git submodule update
#+end_src

To run the native code:

#+begin_src sh
make && bin/main
#+end_src

To run the emscripten code:

#+begin_src sh
make www
#+end_src

and then tell the webserver to serve the files from =www/=.

The Emscripten-ed wasm output is [[http://www.redblobgames.com/x/1535/][here]].

I've also written a partial =CMakeLists.txt= file but am not using it yet.

To disable WebAssembly, take out the ~-s WASM=1~ flag in the Makefile.

The font included in this project is [[https://www.google.com/fonts/specimen/Droid+Sans][Droid Sans]], under the Apache License v2. The ImGui library includes the Proggy font.

